# Site settings
title: By Fire Be Purged
email: kelsin@valefor.com
description: >
  This is the main website for the By Fire Be Purged raiding API. This API
  can help manage raid scheduling and seating for World of Warcraft.
baseurl: "/"
url: "http://byfirebepurged.com"
twitter_username: kelsin5
github_username:  kelsin

# Markdown settings
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
    - strikethrough
    - smart

# Syntax Highlighting
highlighter: pygments

# Approved github jekyll plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Ignore files meant for building
exclude:
  - .bowerrc
  - .bundle
  - .ruby-version
  - bower.json
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
